export const KILIMANJARO_ROUTES = [
  {
    id: "machame",
    title: "Machame Route",
    subtitle: "The Whiskey Route",
    price: 5000,
    image: "/images/machame.jpg",
    duration: "7 Days",
    difficulty: "Challenging",
    successRate: "85%",
    description: "The most popular route. Known for 'climb high, sleep low' acclimatization.",
    features: ["Scenic variety", "High success rate", "Great acclimatization"],
  },
  {
    id: "marangu",
    title: "Marangu Route",
    subtitle: "The Coca-Cola Route",
    price: 4500,
    image: "/images/marangu.jpg",
    duration: "6 Days",
    difficulty: "Moderate",
    successRate: "70%",
    description: "The only route offering hut accommodations rather than tents.",
    features: ["Hut stays", "Gradual ascent", "Historical route"],
  },
  {
    id: "lemosho",
    title: "Lemosho Route",
    subtitle: "The Scenic Western Approach",
    price: 5500,
    image: "/images/lemosho.jpg",
    duration: "8 Days",
    difficulty: "Moderate/Challenging",
    successRate: "90%",
    description: "Considered the most beautiful route with excellent acclimatization.",
    features: ["Low traffic", "Incredible views", "High success rate"],
  },
  {
    id: "rongai",
    title: "Rongai Route",
    subtitle: "The Remote Northern Approach",
    price: 4800,
    image: "/images/rongai.jpg",
    duration: "7 Days",
    difficulty: "Moderate",
    successRate: "80%",
    description: "The only route approaching from the north; drier and very remote.",
    features: ["Remote wilderness", "Less crowded", "Drier climate"],
  },
  {
    id: "northern-circuit",
    title: "Northern Circuit",
    subtitle: "The Ultimate Acclimatization",
    price: 6000,
    image: "/images/northern.jpg",
    duration: "9 Days",
    difficulty: "Challenging",
    successRate: "95%",
    description: "The longest route, traversing the quiet northern slopes.",
    features: ["Highest success rate", "Panoramic views", "Total solitude"],
  },
  {
    id: "shira",
    title: "Shira Route",
    subtitle: "The Plateau Crossing",
    price: 5300,
    image: "/images/shira.jpg",
    duration: "7 Days",
    difficulty: "Challenging",
    successRate: "85%",
    description: "Starts at a high elevation, offering a dramatic approach.",
    features: ["Unique plateau start", "Spectacular scenery", "Varied terrain"],
  },
  {
    id: "umbwe",
    title: "Umbwe Route",
    subtitle: "The Steepest Ascent",
    price: 5100,
    image: "/images/umbwe.jpg",
    duration: "6 Days",
    difficulty: "Very Challenging",
    successRate: "65%",
    description: "The shortest and steepest route, favored by experienced climbers.",
    features: ["Dense forest path", "Quick summit attempt", "For experts only"],
  }
];